---
  - name: download and uncompress
    shell: cd /tmp;rm nagios*.tar.gz;wget -O nagios.tar.gz --no-check-certificate https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz;tar -zxf nagios.tar.gz;mv nagios-4.4.5 nagios
    become: true

  - name: configure and make all
    shell: cd /tmp/nagios;./configure --with-mail=/usr/sbin/sendmail --with-httpd-conf=/etc/apache2/sites-enabled;make all;
    become: true

  - name: configure and make all
    shell: cd /tmp/nagios;./configure --with-mail=/usr/sbin/sendmail --with-httpd-conf=/etc/apache2/sites-enabled;make all;
    become: true

  - name: create nagios user homedir
    file:
      path: /home/nagios
      state: directory
      owner: nagios
      group: nagios
      mode: 0775
    become: true
